### ISSUE TITLE
Problem with GCC 8: Example does not compile b/c `poly::unerase_poly` is not declared.

### ISSUE THREAD

**Issue by tinloaf** [ldionne/dyno#55] opened 2018-09-04 13:20 UTC
Hi. I'm trying to compile the "long-form" example from the readme (i.e., the example without using the macro). However, it fails because apparently, `poly::unerase_poly` is not declared (at least not in a way that GCC expects it):

```
lukas@i11pcbarth ~/tmp/mnwe/dyno $ g++ --std=c++17 -I /home/lukas/src/dyno/include/ -I /home/lukas/opt/boost_install/include/ ./example.hpp 
In file included from /home/lukas/src/dyno/include/dyno/macro.hpp:33,
                 from /home/lukas/src/dyno/include/dyno.hpp:11,
                 from ./example.hpp:1:
/home/lukas/src/dyno/include/dyno/poly.hpp: In instantiation of ‘dyno::poly<Concept, Storage, VTablePolicy>::virtual_impl(dyno::method_t<R(T ...) const>, Function) const [with R = void; T = {std::basic_ostream<char, std::char_traits<char> >&}; Function = dyno::detail::string<'d', 'r', 'a', 'w'>; Concept = Drawable; Storage = dyno::remote_storage; VTablePolicy = dyno::vtable<dyno::remote<dyno::everything> >]::<lambda(auto:17&& ...)> [with auto:17 = {std::basic_ostream<char, std::char_traits<char> >&}]’:
./example.hpp:22:33:   required from here
/home/lukas/src/dyno/include/dyno/poly.hpp:221:19: error: ‘unerase_poly’ was not declared in this scope
                   poly::unerase_poly<T>(static_cast<decltype(args)&&>(args))...);
                   ^~~~

```
 
The directory `/home/lukas/src/dyno/` contains a current git HEAD checkout, and `/home/lukas/opt/boost_install` contains a boost 1.66 (including Boost.Hana). I'm using GCC 8 on Ubuntu:

```
lukas@i11pcbarth ~/tmp/mnwe/dyno $ g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.1.0-5ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.1.0 (Ubuntu 8.1.0-5ubuntu1~16.04) 
```

For completeness sake, here is the complete content of the `example.hpp` that I'm trying to compile:

```c++
#include <dyno.hpp>
#include <iostream>
using namespace dyno::literals;

// Define the interface of something that can be drawn
struct Drawable : decltype(dyno::requires(
  "draw"_s = dyno::method<void (std::ostream&) const>
)) { };

// Define how concrete types can fulfill that interface
template <typename T>
auto const dyno::default_concept_map<Drawable, T> = dyno::make_concept_map(
  "draw"_s = [](T const& self, std::ostream& out) { self.draw(out); }
);

// Define an object that can hold anything that can be drawn.
struct drawable {
  template <typename T>
  drawable(T x) : poly_{x} { }

  void draw(std::ostream& out) const
  { poly_.virtual_("draw"_s)(out); }

private:
  dyno::poly<Drawable> poly_;
};

struct Square {
  void draw(std::ostream& out) const { out << "Square"; }
};

struct Circle {
  void draw(std::ostream& out) const { out << "Circle"; }
};

void f(drawable const& d) {
  d.draw(std::cout);
}

int main() {
  f(Square{}); // prints Square
  f(Circle{}); // prints Circle
}
```

**Comment by tinloaf** [comment] 2018-09-04 13:52
Update: Funny thing is, clang-5.0 and gcc-7 both compile it (though clang warns about string literal operators being a GNU extension):

```
lukas@i11pcbarth ~/tmp/mnwe/dyno $ /usr/bin/clang-5.0  --std=c++17 -I /home/lukas/src/dyno/include/ -I /home/lukas/opt/boost_install/include/ ./example.hpp 
In file included from ./example.hpp:1:
In file included from /home/lukas/src/dyno/include/dyno.hpp:8:
In file included from /home/lukas/src/dyno/include/dyno/builtin.hpp:8:
In file included from /home/lukas/src/dyno/include/dyno/concept.hpp:8:
/home/lukas/src/dyno/include/dyno/detail/dsl.hpp:124:18: warning: string literal operator templates are a GNU extension [-Wgnu-string-literal-operator-template]
  constexpr auto operator""_s() { return detail::string<c...>{}; }
                 ^
1 warning generated.
```

```
lukas@i11pcbarth ~/tmp/mnwe/dyno $ /usr/bin/g++-7  --std=c++17 -I /home/lukas/src/dyno/include/ -I /home/lukas/opt/boost_install/include/ ./example.hpp 
lukas@i11pcbarth ~/tmp/mnwe/dyno $ 
```

Thus, this might be a GCC-8 bug / regression? My feeling is that something in the `enable_if`s for `poly::unerase_poly` is fishy, but I really don't understand what's going on there.

**Comment by gchoinka** [comment] 2018-09-23 16:56
I've run in in to the same problem with my travis build and gcc-8.0
It seems that gcc-8.2 compiles the sources fine.

**Comment by ldionne** [comment] 2018-09-30 20:10
Yes, this seems like a GCC bug. I can reproduce with GCC 8.1. I was not able to find a workaround that did not involve making `unerase_poly` a non-static member function, which is not satisfactory since that requires capturing `this` in the function returned by `virtual_impl` even when `this` would not otherwise need to be captured. I'll close this as "wontfix" but I'm open to workarounds if somebody has one.

**Closed by ldionne** 2018-09-30 20:10 UTC
